name: UnitTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1.8.0
    - name: Setup Swift 5.5
      with:
        swift-version: "5.5.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
